github.com:
    users:
        ryclondo:
            oauth_token: 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
    git_protocol: ssh
    user: ryclondo
    oauth_token: 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
